<?php

namespace Database\Seeders;

use App\Models\Abogado;
use Illuminate\Database\Seeder;

class AbogadoSeeder extends Seeder
{
    public function run(): void
    {
        $abogados = [
            [
                'nombre' => 'Dr. Carlos Andrés Ramírez',
                'documento' => '12345678',
                'especialidad' => 'transito',
                'tarjeta_profesional' => 'TP-12345',
                'telefono' => '6011111111',
                'celular' => '3101111111',
                'email' => 'carlos.ramirez@abogados.com',
                'direccion' => 'Calle 72 # 10-15, Bogotá',
                'ciudad' => 'Bogotá',
                'honorarios_hora' => 150000,
                'porcentaje_comision' => 20.00,
                'areas_practica' => 'Derecho de tránsito, comparendos, controversias, recursos de apelación',
                'formacion_academica' => 'Universidad Nacional de Colombia - Especialización en Derecho de Tránsito',
                'experiencia' => '15 años de experiencia en derecho de tránsito, exfuncionario de la Secretaría de Movilidad',
                'disponible' => true,
                'activo' => true,
            ],
            [
                'nombre' => 'Dra. María Fernanda López',
                'documento' => '87654321',
                'especialidad' => 'penal',
                'tarjeta_profesional' => 'TP-54321',
                'telefono' => '6042222222',
                'celular' => '3102222222',
                'email' => 'maria.lopez@abogados.com',
                'direccion' => 'Carrera 43A # 1-50, Medellín',
                'ciudad' => 'Medellín',
                'honorarios_hora' => 180000,
                'porcentaje_comision' => 25.00,
                'areas_practica' => 'Derecho penal, comparendos penales, audiencias, defensa técnica',
                'formacion_academica' => 'Universidad de Antioquia - Maestría en Derecho Penal',
                'experiencia' => '12 años de experiencia, especialista en delitos de tránsito con resultado de lesiones',
                'disponible' => true,
                'activo' => true,
            ],
            [
                'nombre' => 'Dr. Roberto Sánchez Mendoza',
                'documento' => '11223344',
                'especialidad' => 'civil',
                'tarjeta_profesional' => 'TP-33445',
                'telefono' => '6023333333',
                'celular' => '3103333333',
                'email' => 'roberto.sanchez@abogados.com',
                'direccion' => 'Avenida 4N # 15-20, Cali',
                'ciudad' => 'Cali',
                'honorarios_hora' => 120000,
                'porcentaje_comision' => 18.00,
                'areas_practica' => 'Derecho civil, responsabilidad civil extracontractual, daños y perjuicios',
                'formacion_academica' => 'Universidad del Valle - Especialización en Derecho Civil',
                'experiencia' => '10 años de experiencia en reclamaciones por accidentes de tránsito',
                'disponible' => true,
                'activo' => true,
            ],
            [
                'nombre' => 'Dra. Ana Lucía Gómez',
                'documento' => '55667788',
                'especialidad' => 'laboral',
                'tarjeta_profesional' => 'TP-66778',
                'telefono' => '6054444444',
                'celular' => '3104444444',
                'email' => 'ana.gomez@abogados.com',
                'direccion' => 'Calle 84 # 45-30, Barranquilla',
                'ciudad' => 'Barranquilla',
                'honorarios_hora' => 130000,
                'porcentaje_comision' => 22.00,
                'areas_practica' => 'Derecho laboral, accidentes de trabajo, enfermedades laborales',
                'formacion_academica' => 'Universidad del Norte - Especialización en Derecho Laboral',
                'experiencia' => '8 años de experiencia, asesora de empresas de transporte',
                'disponible' => true,
                'activo' => true,
            ],
            [
                'nombre' => 'Dr. Javier Antonio Pérez',
                'documento' => '99887766',
                'especialidad' => 'transito',
                'tarjeta_profesional' => 'TP-88776',
                'telefono' => '6055555555',
                'celular' => '3105555555',
                'email' => 'javier.perez@abogados.com',
                'direccion' => 'Avenida San Martín # 20-15, Cartagena',
                'ciudad' => 'Cartagena',
                'honorarios_hora' => 140000,
                'porcentaje_comision' => 19.50,
                'areas_practica' => 'Derecho administrativo, trámites ante secretarías de tránsito, recursos',
                'formacion_academica' => 'Universidad de Cartagena - Especialización en Derecho Administrativo',
                'experiencia' => '14 años de experiencia, exasesor de la Secretaría de Tránsito de Cartagena',
                'disponible' => true,
                'activo' => true,
            ],
            [
                'nombre' => 'Dra. Sandra Milena Ruiz',
                'documento' => '22334455',
                'especialidad' => 'comercial',
                'tarjeta_profesional' => 'TP-34455',
                'telefono' => '6016666666',
                'celular' => '3106666666',
                'email' => 'sandra.ruiz@abogados.com',
                'direccion' => 'Calle 93 # 12-45, Bogotá',
                'ciudad' => 'Bogotá',
                'honorarios_hora' => 160000,
                'porcentaje_comision' => 21.00,
                'areas_practica' => 'Derecho comercial, contratos de transporte, seguros, reaseguros',
                'formacion_academica' => 'Universidad de los Andes - Maestría en Derecho Comercial',
                'experiencia' => '11 años de experiencia en derecho de seguros y transporte comercial',
                'disponible' => true,
                'activo' => true,
            ],
            [
                'nombre' => 'Dr. Luis Fernando Torres',
                'documento' => '66778899',
                'especialidad' => 'administrativo',
                'tarjeta_profesional' => 'TP-77889',
                'telefono' => '6047777777',
                'celular' => '3107777777',
                'email' => 'luis.torres@abogados.com',
                'direccion' => 'Carrera 65 # 30-10, Medellín',
                'ciudad' => 'Medellín',
                'honorarios_hora' => 135000,
                'porcentaje_comision' => 17.50,
                'areas_practica' => 'Derecho administrativo, procedimientos sancionatorios, recursos de reposición',
                'formacion_academica' => 'Universidad EAFIT - Especialización en Derecho Administrativo',
                'experiencia' => '9 años de experiencia, asesor de entidades públicas de transporte',
                'disponible' => true,
                'activo' => true,
            ],
            [
                'nombre' => 'Dra. Patricia Elena Castro',
                'documento' => '33445566',
                'especialidad' => 'constitucional',
                'tarjeta_profesional' => 'TP-44556',
                'telefono' => '6028888888',
                'celular' => '3108888888',
                'email' => 'patricia.castro@abogados.com',
                'direccion' => 'Avenida 3N # 25-50, Cali',
                'ciudad' => 'Cali',
                'honorarios_hora' => 190000,
                'porcentaje_comision' => 23.00,
                'areas_practica' => 'Derecho constitucional, tutelas, acciones de cumplimiento, derechos fundamentales',
                'formacion_academica' => 'Universidad Javeriana - Maestría en Derecho Constitucional',
                'experiencia' => '13 años de experiencia, especialista en tutelas por derechos de movilidad',
                'disponible' => false, // No disponible temporalmente
                'activo' => true,
            ],
            [
                'nombre' => 'Dr. Alfonso Rodríguez',
                'documento' => '44556677',
                'especialidad' => 'otro',
                'tarjeta_profesional' => 'TP-55667',
                'telefono' => '6059999999',
                'celular' => '3109999999',
                'email' => 'alfonso.rodriguez@abogados.com',
                'direccion' => 'Calle 100 # 80-60, Barranquilla',
                'ciudad' => 'Barranquilla',
                'honorarios_hora' => 110000,
                'porcentaje_comision' => 15.00,
                'areas_practica' => 'Derecho de familia, sucesiones, mediación y conciliación',
                'formacion_academica' => 'Universidad Sergio Arboleda - Especialización en Mediación',
                'experiencia' => '7 años de experiencia, mediador certificado en conflictos de tránsito',
                'disponible' => true,
                'activo' => false, // Inactivo
            ],
            [
                'nombre' => 'Dra. Carmen Rosa Vargas',
                'documento' => '77889900',
                'especialidad' => 'transito',
                'tarjeta_profesional' => 'TP-88990',
                'telefono' => '6050000000',
                'celular' => '3100000000',
                'email' => 'carmen.vargas@abogados.com',
                'direccion' => 'Avenida Pedro de Heredia # 45-20, Cartagena',
                'ciudad' => 'Cartagena',
                'honorarios_hora' => 125000,
                'porcentaje_comision' => 16.50,
                'areas_practica' => 'Derecho ambiental, trámites ambientales para transporte, licencias',
                'formacion_academica' => 'Universidad de la Costa - Especialización en Derecho Ambiental',
                'experiencia' => '6 años de experiencia, asesora ambiental para empresas de transporte',
                'disponible' => true,
                'activo' => true,
            ],
        ];

        foreach ($abogados as $abogadoData) {
            Abogado::create($abogadoData);
        }

        $this->command->info('✅ 10 Abogados creados exitosamente');
        $this->command->info('   👨‍⚖️  5 especializados en tránsito');
        $this->command->info('   ⚖️  1 inactivo y 1 no disponible temporalmente');
    }
}